server.port=8080
spring.application.name=cicd-compass-app

# Default configs that can be overridden via Env Variables
app.name=${APP_NAME:cicd-compass-app}
app.version=${APP_VERSION:v1.0.0}
app.environment=${APP_ENV:local}
app.region=${APP_REGION:ap-south-1}
app.buildNumber=${APP_BUILD_NUMBER:local-dev}